
# - name: Install artifact and create configuration files
#   ansible.builtin.unarchive:
#     src: /tmp/demo-app-{{ semaphore_vars.task_details.incoming_version }}.tar.gz
#     dest: /tmp

- name: Pull app image
  community.docker.docker_image:
    name: "{{ app_image }}"
    source: pull

- name: Stop existing container if running
  community.docker.docker_container:
    name: "{{ app_name }}"
    state: absent
    force_kill: true
    timeout: 10

- name: Run new container
  community.docker.docker_container:
    name: "{{ app_name }}"
    image: "{{ app_image }}"
    restart_policy: unless-stopped
    published_ports:
      - "{{ app_port }}:3000"

# - name: Print installed version
#   debug:
#     msg: "Version {{ semaphore_vars.task_details.incoming_version }} was installed."
