- name: Dump ALL keys and values from semaphore_vars individually
  ansible.builtin.debug:
    var: item
  with_dict: "{{ semaphore_vars }}"

- name: Pull app image
  community.docker.docker_image:
    name: "{{ app_image }}"
    source: pull

- name: Stop existing container if running
  community.docker.docker_container:
    name: "{{ app_name }}"
    state: absent
    force_kill: true
    timeout: 10

- name: Run new container
  community.docker.docker_container:
    name: "{{ app_name }}"
    image: "{{ app_image }}"
    restart_policy: unless-stopped
    published_ports:
      - "{{ app_port }}:3000"

- name: Wait for the app to be healthy
  ansible.builtin.uri:
    url: "http://{{ inventory_hostname }}:{{ app_port }}/info"
    method: GET
    status_code: 200
    timeout: 5
  register: healthcheck_response
  retries: 10
  delay: 6
  until: healthcheck_response.status == 200

# - name: Print installed version
#   debug:
#     msg: "Version {{ semaphore_vars.task_details.incoming_version }} was installed."
